#!/bin/sh

# Starts the tt-rss feed update daemon.

set -e

# Must be a valid filename
NAME=ttrss
PIDFILE=/var/www/tt-rss/$NAME.pid
DAEMON='/usr/bin/php /var/www/tt-rss/update.php'
DAEMON_OPTS="-daemon -quiet"

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
cd /var/www/tt-rss/

case "$1" in
  start)
	echo -n "Starting daemon: "$NAME
	start-stop-daemon --start --quiet --chuid www-data:www-data --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS > /dev/null &
	echo "."
	;;
  stop)
	echo -n "Stopping daemon: "$NAME
	start-stop-daemon --stop --quiet --chuid www-data:www-data --oknodo --pidfile $PIDFILE
	echo "."
	;;
  restart)
	echo -n "Restarting daemon: "$NAME
	start-stop-daemon --stop --quiet --chuid www-data:www-data --oknodo --retry 30 --pidfile $PIDFILE
	start-stop-daemon --start --quiet --chuid www-data:www-data --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS > /dev/null &
	echo "."
	;;

  *)
	echo "Usage: "$1" {start|stop|restart}"
	exit 1
esac

exit 0

